import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { PropsWithChildren } from "react";
import { Providers } from "./providers";
import NextTopLoader from "nextjs-toploader";
import { Header } from "@/components/Layout/header";
import Footer from "@/components/Layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Auction App",
  description: "Generated by nextJs",
};

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
           <NextTopLoader color="#5750F1" showSpinner={false} />
           <div className="w-100 bg-light text-dark">
              <Header />
           </div>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
